jobs:
  - name: jobA
    parameters:
      inputFile: classpath:data/input.txt
    schedule:
      type: cron
      expression: "0 */1 * * * *"

    steps:
      - name: step1
        type: chunk
        chunkSize: 2

        reader:
          type: bean
          bean: simpleStringReader

        processor:
          type: bean
          bean: upperCaseProcessor

        writer:
          type: bean
          bean: consoleWriter

      - name: step2
        type: chunk
        chunkSize: 2

        reader:
          type: jdbc
          sql: select id, name, status from input_data where status = :status
          params:
            status: NEW
          rowMapper: inputDataRowMapper

        processor:
          type: bean
          bean: inputToOutputProcessor

        writer:
          type: jdbc
          sql: >
            INSERT INTO output_data (name, processed_at)
            VALUES (:name, :processedAt)

#  - name: jobB
#    parameters:
#      inputFile: classpath:data/input.txt
#    schedule:
#      type: cron
#      expression: "30 */1 * * * *"
#    steps:
#      - name: step1
#        type: tasklet
#        tasklet: cleanTempFileTasklet
#        params:
#          path: /tmp
#      - name: step2
#        type: chunk
#        chunkSize: 2
#
#        reader:
#          type: bean
#          bean: simpleStringReader
#
#        processor:
#          bean: lowerCaseProcessor
#
#        writer:
#          bean: consoleWriter